### ISSUE TITLE
30 media objects don't seem to have metadata or masterfiles

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#124]
## Description

The following media objects don't have metadata or master files. Can these be deleted? 

http://media.northwestern.edu/media_objects/t148fh13t
http://media.northwestern.edu/media_objects/mg74qm15t
http://media.northwestern.edu/media_objects/n870zq887
http://media.northwestern.edu/media_objects/8c97kq52z
http://media.northwestern.edu/media_objects/736664542
http://media.northwestern.edu/media_objects/47429921g
http://media.northwestern.edu/media_objects/pr76f350t
http://media.northwestern.edu/media_objects/xk81jk50j
http://media.northwestern.edu/media_objects/6682x402r
http://media.northwestern.edu/media_objects/0v838064w
http://media.northwestern.edu/media_objects/k643b1275
http://media.northwestern.edu/media_objects/gt54kn11k
http://media.northwestern.edu/media_objects/3x816m66s
http://media.northwestern.edu/media_objects/d791sg25p
http://media.northwestern.edu/media_objects/1831cj99w
http://media.northwestern.edu/media_objects/1n79h444s
http://media.northwestern.edu/media_objects/b8515n49s
http://media.northwestern.edu/media_objects/gf06g278x
http://media.northwestern.edu/media_objects/ww72bb54s
http://media.northwestern.edu/media_objects/d791sg26z
http://media.northwestern.edu/media_objects/dr26xx49n
http://media.northwestern.edu/media_objects/sx61dm405
http://media.northwestern.edu/media_objects/0z708w57j
http://media.northwestern.edu/media_objects/sf2685314
http://media.northwestern.edu/media_objects/sb397838t
http://media.northwestern.edu/media_objects/dv13zt38c
http://media.northwestern.edu/media_objects/q237hs128
http://media.northwestern.edu/media_objects/nz805z82j
http://media.northwestern.edu/media_objects/g445cd32h
http://media.northwestern.edu/media_objects/t148fh30g

**Comment by davidschober** [comment]
Note these look like someone started to create an object and then stopped.

**Comment by jenyoung** [comment]
deleted all but two from AVR 6 and AVR 4

Two left from AVR 6 --I hesitated since they are Course Audio objects with metadata.

http://media.northwestern.edu/media_objects/t148fh13t - AVR 4 object -https://legacy.media.library.northwestern.edu/media_objects/numedia:10247
![image](https://user-images.githubusercontent.com/2250501/27059593-f0bdad06-4f9c-11e7-8004-a4c7f7d5d781.png)

http://media.northwestern.edu/media_objects/v405s938k - duplicate record of http://media.northwestern.edu/media_objects/mg74qm15t 
![image](https://user-images.githubusercontent.com/2250501/27059614-15df454a-4f9d-11e7-9a1c-0efd868ed34a.png)

**Comment by davidschober** [comment]
Moving the final two above to a new issue.
