### ISSUE TITLE
Playlist auto advancing, and not showing clips.

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#230]
## Description

When a playlist with a segment as the first item loaded, the player shows the full length of the movie until a user clicks on the segment. This seems unique to our instance of Avalon (the current pawpaw instance does not have this bug.

## To recreate:

Create a public or a private playlist
add a segment 
add another segment
add another one
go to playlist, note that the full media object loads in the player rather than the segment
click on the segment, see that it loads the segment. 

EXAMPLE : https://media.northwestern.edu/playlists/45

![playlistbug](https://user-images.githubusercontent.com/4803230/28591395-2c467ea0-714b-11e7-9ac6-468c4cbbd4f0.gif)

Sample Playlist:

https://media.northwestern.edu/playlists/45/edit

**Comment by davidschober** [comment]
@carrickr or @mbklein do you want to take a look at this one?

**Comment by davidschober** [comment]
@carrickr @adamjarling can you dig into this one a bit? It's petty serious. On pawpaw, we don't see this error at all.

**Comment by davidschober** [comment]
@mbklein and @carrickr just wondering if anyone has had a chance to take a guess at what might be happening here.

**Comment by davidschober** [comment]
Note, @carrickr and I were working through this. It appears that it might be a streaming issue of some kind (RTMP).

**Comment by davidschober** [comment]
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (6534122_10thin.m3u8, line 0)
[Error] Failed to load resource: The file “messages.json” couldn’t be opened because there is no such file. (messages.json, line 0)

**Comment by davidschober** [comment]
@mbklein @carrickr This has been open for a bit. There's faculty training sessions on sept 14. Can someone dig into it?

**Comment by carrickr** [comment]
After some digging:

When RTMP streaming the file is slow to load but does load, however it loads at 0:00 (start of the masterfile) rather than the time stamp.

On HLS (iOS) the clip does not playback at all, stalls out loading.  

We definitely need to solve the HLS problem, however my question (feedback welcome @mbklein ) is if we should solve it here on Avalon 6 with Media Element 2 or push on Avalon 6.2 with the upgraded media element and then solve it there.  Once we have a AWS-Staging branch of Avalon 6.2 up for NU we can see if the problem persists with the new ME and respond accordingly.

**Comment by carrickr** [comment]
On Chrome I'm seeing an infinite look regarding preload never completing (check dev console default level events)

**Comment by carrickr** [comment]
Cookie now authorizes, but it's still not jumping, still digging into this.

**Comment by davidschober** [comment]
@carrickr did were you ever able to dig a bit more into this?

**Comment by davidschober** [comment]
@carrickr @mbklein I'm confused. Does this have an open PR?

**Comment by davidschober** [comment]
Testing with 6.2 in staging.. Playlists seem to still be totally broken.

@adamjarling and @carrickr or @mbklein can you take  a look.

To recreate:

1. Create a playlist
2. add more than one thing to playlist
3. go to playlist
4. See that the first item is skipped as it seems to not be able to negotiate access
5. See that at times clips are not respected.

**Comment by carrickr** [comment]
dug into this and talked to @adamjarling 

This is hard to debug because it uses the old coffeescript that is both a mess in terms of code quality and just hard to track with a debugger.  This behavior is also entirely rewritten using better practices and code in 6.3 which we are going to aggressively push out early in 2018.  The advice was if it all possible punt to 6.3.  Worst case is if this continues in 6.3 it will be much easier to debug and fix.  Plus any fix we did for 6.2 would not port over due to the total rewrite.  If POs are happy with this we can close as a won't fix.

**Comment by davidschober** [comment]
Abandoning as won't fix. We are going regroup around 6.3
