### ISSUE TITLE
create staging s3 credentials

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#283]
Create credentials for staging s3. We should create a single cyberduck script for staging that everyone can share.

**Comment by carrickr** [comment]
@davidschober I made a wiki page in nextgen since the script has key pairs in it and avalon isn't private.

https://github.com/nulib/next-generation-repository/wiki/Connecting-to-the-AVR-Staging-Dropbox

We probably need to move it somewhere else since most of our tests don't have github accounts, box perhaps?

**Comment by carrickr** [comment]
This script should auto log you in to `avr-masterfiles-staging-rd56wk8/dropbox` on S3
