### ISSUE TITLE
Need help getting ~16,000 audio files to S3

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#357]
## Description
I'm trying to ingest the School of Music Concert Recordings collection, which consists of about 16,000 audio files. Not trying to do it all at once, but Cyberduck won't upload into the S3 bucket because there are so many files in the directory. 

The files are at dl17/Music_CD_Collection

## Done looks like

I need advice on another way to ingest (not Cyberduck), or for someone to copy all the audio files into the S3 bucket for me.

**Comment by davidschober** [comment]
@carrickr can you work with @laura-alagna to get these files up to s3?

**Comment by Toputnal** [comment]
nulib/devops#222 is tracking this work.

**Comment by Toputnal** [comment]
the server awslync.library is hooked to the isilon and has the awscli installed.  Repository shares are all mounted (via nfs automounts) at /repository  @carrickr @davidschober @mbklein

**Comment by carrickr** [comment]
The sync operation is underway, 704 mpbs speeds, very nice.  I will check the process first thing on Monday

**Comment by carrickr** [comment]
Missing `bienen0011_13.wav` on DL17

**Comment by carrickr** [comment]
As a slackup for the ingest, 1787 media objects are ingested, ~160 pending

Of the pending, 82 are due to invalid files.  21 of them are use naming errors (the student who digitized it typed the name wrong) and the others appear to be the student skipped the file, so Laura will break out the CDs and get those missing files, she is currently in the process of renaming the other 21.  The names weren't messed up in a consistent way, so no auto fix vis script option.  

The other pending are due to catalog errors and Jen has reached out to the catalogers for those.

We also have 41 files that exist but are corrupted (see issue #363).  Laura will get those off the CD as well.  With these the Media Object was created, but when it came time to transcode the file, the transcode failed.  As an example see:

https://media.northwestern.edu/media_objects/8p58pf062

**Comment by davidschober** [comment]
@laura-alagna do you want to use #363 for the general cleanup? or create a separate rename issue?

**Comment by laura-alagna** [comment]
@davidschober I'll break out another issue
