### ISSUE TITLE
AVR: Firefox won't stream some videos through canvas

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#396]
## Description

avr is having an intermittent problem streaming certain videos in canvas. 

## To Recreate

- Go to canvas.northwestern.edu
- login with creds that have access to a course
- go to a Avalon Testing course (or other)
- to to "Library Media"
- stream a video
- go back to "library media"
- try to stream a video
- see that the start and end times are 0:00 -->0:00

**Comment by mbklein** [comment]
I believe there are two culprits here: Caching and CORS. When the page is loaded from the server, MediaElement and Firefox send the correct `Origin` header to the streaming server, and the streaming server responds with the correct `Access-Control-Allow-Origin` header. But when the page is reloaded from cache, The `Origin` header doesn't get sent, meaning there is no `Access-Control-Allow-Origin` header in the response, triggering a CORS rejection from the browser. Right-clicking the AVR frame and selecting "Reload Frame" makes it work, but only until the next cached navigation.

The solution _might_ be as simple as adding a random `?req=RANDOM_NUMBER` parameter to every link on the search results page, preventing the detail pages from being cached. (Or adding the `Cache-Control: no-cache` header to all detail pages, which is actually the _right_ way to do that.)

The problem is going to be testing the solution. There's a Canvas docker image I might be able to set up later for local testing, but we don't have a good link between A&RT's staging Canvas and our staging AVR.

**Comment by davidschober** [comment]
closing. too hard to replicated. THis was a very specific ff version
