### ISSUE TITLE
Migration Timeline for Avalon 6.x AWS pilot

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#46]
## TIMELINE

- skinning @adamjarling May 11-May 21. 
- System Stable @mbklein May 15
- Migration path/ test 2-3 collections @carrickr  May 15
- Migration Frist run @carrickr @mbklein  May 30 
- Metadata testing ( @jenyoung ) June 1 -7
- Testing (Everyone) June 5-12 (June 8 Cecile and Molly will be testing)
- Tell Molly/ etc that new material should be loaded in new system **only** June 5?
- Production Testing June 12

Nicole and David out June 5-9.  Nicole out June 12 week as well.

**INTERCESSION June 12-16**

- Final Migration (if necessary) June 14
- Go  Live June 15

**Classes Start June 19**

## Critical Messaging and tasks

- [ ] Demo new system and workflow to Molly, Cecile, etc. May 29-June 2 (@Nic4Images to create meeting to demo and show them at their desks with @davidschober)
- [ ] Migrate test data, start testing @carrickr #60 #41 #61  
- [x] Molly, etc, will need to use FTP for batches. But there are no limits on web uploads
- [x] text needed About, Help (from current footer and https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+User+Guide), and Contact Us @Nic4Images #62 #63 

## Risks -- any of these can put us off time

- Migration goes bad/ off
- Training doesn't go well (users are confused, things don't work)
- Canvas integration fails
- Authentication stops working
- Devops has issues with security, etc.

**Comment by davidschober** [comment]
@mbklein, @adamjarling  and @carrickr can you review and approve this timeline (this is our golive shortlist)

**Comment by adamjarling** [comment]
From front-end / skinning angle, looks good.  Skinning work should be pretty far along by next week.

**Comment by Nic4Images** [comment]
Copying from email to GitHub ..  

From: Nicole Finzer <n-finzer@northwestern.edu>
Date: Thursday, May 18, 2017 at 11:41 AM
To: Carolyn Caizzi <carolyn.caizzi@northwestern.edu>
Cc: David Schober <david.schober@northwestern.edu>, Cecile-Anne Sison <c-sison2@northwestern.edu>, Molly Zolnay <m-zolnay@northwestern.edu>
Subject: AVR 6.0 Testing
 
Hi Carolyn,
 
David and I met with Molly and Cecile this morning:
 
MBK and David will meet with or email Kelly to discuss the test instance of Canvas
 
David will lead a train the trainer session on June 1, 2017
Cecile, Nicole, Pete, Alex, Matt Taylor, Kurt, Nathalie, and Molly are invited
Molly is out June 1, 2017 so Cecile will train the trainer with Molly on June 8, 2017
David will determine when the test instance of AVR 6.0 can be shared with participants and share that with Nicole who will disseminate it to attendees
 
·         We agreed on June 08, 2017 for testing.
o   Molly and Cecile will test their workflows and send feedback by email to you, me, and David by 5PM
o   David noted he will be in Italy June 5-9, 2017 so you may need to step in due to the time difference. (We will leave this to you two to work out.)
 
·         If all goes well with testing AVR 6.0 will roll to production on June 12, 2017
 
Many thanks,
 
Nicole

**Comment by jenyoung** [comment]
we need to develop a plan for DCM's involvement in the migration.

**Comment by Nic4Images** [comment]
Enter this info in here or Box:

1. Link to user guide in AVR wiki (like Arch)
2. Whats currently in the AVR footer (find course reserves process and put straight to link)

**Comment by davidschober** [comment]
Closing this. It has become redundant with #19
