### ISSUE TITLE
Fix "add to playlist" styles

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#56]
## Description

When clicking "add to playlist" the styles should match NU's general branding et.c 

![screen shot 2017-05-19 at 3 25 59 pm](https://cloud.githubusercontent.com/assets/4803230/26265676/b1a95dfc-3ca7-11e7-9b77-a31ef4d3f1e6.png)

**Comment by adamjarling** [comment]
@davidschober Good catch.  There's some other Mediaelement styles which need to be updated as well.  I'll add to the ticket.

**Comment by adamjarling** [comment]
@mbklein @carrickr How do I add content (video/audio) to http://avalon.repo.rdc.library.northwestern.edu/ ?   Or is this just display only for now?

**Comment by adamjarling** [comment]
This must have gotten fixed in some round of updates.  Note the gap should get corrected on a previous fix.

![nu-avalon-aws-add-to-playlist-fixed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e681d7229482a580e7f242b34ebd952d426a672649b327719cef21ac56360706171bf853444d04bea6d37ef5f22e7a98590ce9843b5c22c63814f9bf864bbd53ba24de4f86bebf8c5edcfa7f74b9dfd0126754505a9bf54f36a2934acc51f148e64f50a6103064e7647b.png)
