### ISSUE TITLE
list of files still remaining on Alps after script working again

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#8]
I went thru my initial assessment again comparing what had been removed after the script was made to work again on Alps. There are still files that should be removed on Alps. I do not know if they are in the farchive.

[alps_list_2016.xlsx](https://github.com/nulib/avalon/files/649521/alps_list_2016.xlsx)

**Comment by davidschober** [comment]
@mbklein and @Toputnal can you look at this list and confirm that these files are moved and can be removed?

**Comment by davidschober** [comment]
We might want to add more space by using an isilon share @david.schober no, we cannot add any space to Alps.  But we can request a new isilon share be created and mounted to Alps and then move all data the the lsilon the be sorted out later, thus clearing the locally attached storage on Alps.

[3:54]  
To the isilon, rather

**Comment by rtrautve1** [comment]
MBK will do an audit - run through everything that is on Avalon.  After that - we can delete these files off of Alps

**Comment by davidschober** [comment]
@mbklein can you update after you're back next week?

**Comment by ccaizzi** [comment]
closing because @mbklein said 

"
I’ve taken several passes throught the MasterFiles in Avalon and the files that remain in Avalon’s ingest/dropbox directories. As far as I can tell, all video files that should have been moved to farchived were moved either by Avalon or by my script the last time we had an Isilon quota issue.
 
The files that remain in the dropbox fall into the following categories:
 
1)       1,854 audio files that my previous script missed (.aiff, .wav., .mp3, .m4a), that will have to be status-checked to make sure they’ve been properly ingested before I move them. (A significant number of these files are part of failed batch ingests, so not all of them can be considered “missing” from farchive.)
2)       18 obvious test items (e.g., collections named “Streaming Testing” or copies of the Avalon demo videos).
3)       5 other videos that I have been unable to match to any existing AVR MasterFile objects.
 
I have been unable to come up with an explanation for the before/after size anomaly in the backup report, but I am confident (based on my spot checks on December 7 and my current investigation) that all files that needed to be moved in December were moved either to farchive19 or farchive20. Those files that remain behind can be taken care of quickly once I finish their status checks, and do not represent a particularly significant amount of data in terms of file size (because they are audio).
"
