### ISSUE TITLE
Fedora 4 PIDs updating

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#82]
batch updating of Fedora 4 PIDs 

##Done Looks Like:

[ ] remove ```vpc``` from Fedora 4 URLs 
[ ] Fedora 4 PID should display as ```6682x415t``` instead of ```http://fcrepo.repo.rdc.library.northwestern.edu/rest/66/82/x4/15/6682x415t```

**Comment by mbklein** [comment]
The Fedora 3 and Fedora 4 PIDs in the <recordInfo/> block of the MODS metadata were being applied inconsistently. They were present for migrated objects but not for new objects, and even when present, weren't always formatted/addressed the same way. Since both those pieces of information are represented elsewhere in the record (the `migratedFrom` assertion for the F3 pid and the actual current identifier for the F4 pid), I scrubbed them both from the MODS until we decide once and for all how to track them.

**Comment by davidschober** [comment]
@jenyoung note above ^^^ Let's close this particular issue.

**Comment by jenyoung** [comment]
i'm confused. i thought we did

https://github.com/avalonmediasystem/avalon/issues/1616

**Comment by jenyoung** [comment]
@mbklein @davidschober can we reopen and work on this? see the comment above. i thought we did decide how to handle these.

**Comment by davidschober** [comment]
@mbklein and @carrickr do we need to grab the old pids and put them in the proper place?

**Comment by davidschober** [comment]
@carrickr can you grab this prior to 6.2 upgrade?

**Comment by davidschober** [comment]
@jenyoung can we close this?

**Comment by jenyoung** [comment]
@davidschober I'm not sure. It looks like the `vpc` part is gone. I don't see the identifier in the mods record

**Comment by davidschober** [comment]
@jenyoung I think this issue is super stale. Closing.
